package com.track.distance.enums.encomenda;

public enum Tipo {

    ENTREGUE_AO_DESTINATARIO,
    DESTINATARIO_AUSENTE,
    PROBLEMA_NA_ROTA,
    DEVOLUCAO_AO_DESTINATARIO,
    DEVOLVIDO_AO_DESTINATARIO,
    EM_PREPARACAO,
    ENTREGUE_A_TRANSPORTADORA,
    SAIDA_PARA_ENTREGA,
    EM_TRANSFERENCIA,
    REMESSA_CRIADA;

}
